 name: lint
        uses: Bloc5-Management-et-d-ploiement-de-solutions-Cloud-JValens-f-vrier-2022-Public/guestbook/
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
